### ISSUE TITLE
Fix expertise dropdown data 

### ISSUE THREAD

**Issue by ranwahle** [tikalk/10n1#1]
Expertise dropdown data, on profile setting, the expertise list does not exist and therefore, tit loads an invalid expertise list.

The expertise list should be loaded from the app database instead of an outside source.

- In case the list is invalid, the user should be presented with an error message
- An alert should be sent to the app monitoring service.

**Comment by yinondn** [comment]
Fixed by commit 328787cf3c9dad34470f03b2695a2ef4d124fff1
